### ISSUE TITLE
SeaGlass is not working with Java jdk 7 or higher!!!

### ISSUE THREAD

**Issue by sowndar16** [khuxtable/seaglass#115]
Looks like some packages in java 7 where moved from sun.swing.plaf. So the result is that seaglass.jar is throwing lot of Exceptions!!!!. It's not even working!!!!

/usr/lib/jvm/java-9-oracle/bin/java -javaagent:/usr/java/idea-2018/lib/idea_rt.jar=38151:/usr/java/idea-2018/bin -Dfile.encoding=UTF-8 -classpath /home/sowndar/IdeaProjects/SeaGlassDemo/out/production/SeaGlassDemo:/home/sowndar/IdeaProjects/SeaGlassDemo/lib/seaglasslookandfeel-0.2.jar SeaGlassDemo
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.seaglasslookandfeel.SeaGlassLookAndFeel (file:/home/sowndar/IdeaProjects/SeaGlassDemo/lib/seaglasslookandfeel-0.2.jar) to field javax.swing.border.EtchedBorder.highlight
WARNING: Please consider reporting this to the maintainers of com.seaglasslookandfeel.SeaGlassLookAndFeel
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: sun/swing/plaf/synth/SynthIcon
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.seaglasslookandfeel.SeaGlassLookAndFeel.defineButtons(SeaGlassLookAndFeel.java:1009)
	at com.seaglasslookandfeel.SeaGlassLookAndFeel.getDefaults(SeaGlassLookAndFeel.java:456)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at SeaGlassDemo.<init>(SeaGlassDemo.java:17)
	at SeaGlassDemo$1.run(SeaGlassDemo.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: sun.swing.plaf.synth.SynthIcon
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 28 more

Process finished with exit code 0

**Comment by amaljithev** [comment]
Same error
