### ISSUE TITLE
java.lang.UnsatisfiedLinkError: apple.laf.JRSUIControl.getCFDictionary(Z)J

### ISSUE THREAD

**Issue by GoogleCodeExporter** [khuxtable/seaglass#95]
```
What steps will reproduce the problem?
1. Create a project, using java 7
2. Add seaglass 0.2 as a dependency
3. Run the application

What is the expected output? What do you see instead?
I get the following stacktrace:

Exception in thread "main" java.lang.UnsatisfiedLinkError: 
apple.laf.JRSUIControl.getCFDictionary(Z)J
    at apple.laf.JRSUIControl.getCFDictionary(Native Method)
    at apple.laf.JRSUIControl.<init>(JRSUIControl.java:102)
    at com.apple.laf.AquaPainter$AquaSingleImagePainter.<init>(AquaPainter.java:131)
    at com.apple.laf.AquaPainter.create(AquaPainter.java:45)
    at com.apple.laf.AquaTableHeaderBorder.<init>(AquaTableHeaderBorder.java:45)
    at com.apple.laf.AquaTableHeaderBorder.getListHeaderBorder(AquaTableHeaderBorder.java:50)
    at com.apple.laf.AquaLookAndFeel.initComponentDefaults(AquaLookAndFeel.java:331)
    at com.apple.laf.AquaLookAndFeel.getDefaults(AquaLookAndFeel.java:231)
    at com.seaglasslookandfeel.SeaGlassLookAndFeel.defineAquaSettings(SeaGlassLookAndFeel.java:886)
    at com.seaglasslookandfeel.SeaGlassLookAndFeel.getDefaults(SeaGlassLookAndFeel.java:498)
    at javax.swing.UIManager.setLookAndFeel(UIManager.java:536)
    at javax.swing.UIManager.setLookAndFeel(UIManager.java:580)

What version of the product are you using? On what operating system? What
JRE version?

Operation system:
OS X, version 10.8.2

JRE: 
java version "1.7.0_09"
Java(TM) SE Runtime Environment (build 1.7.0_09-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.5-b02, mixed mode)

Seaglass version:
0.2

```

Original issue reported on code.google.com by `ulrik.le...@gmail.com` on 12 Dec 2012 at 6:32

**Comment by khuxtable** [comment]
I can resolve this. It's trying to get some menu and menu bar settings from Aqua and failing. Java 8 works very differently from the old Apple-provided Java that I developed this with. I can't see that we are getting anything significant from Aqua, so I'm likely to simply remove the code.
